export const oAuth2ProviderNames = [
  { name: "apple", label: "Apple" },
  { name: "google", label: "Google" },
  { name: "microsoft", label: "Microsoft" },
  { name: "yandex", label: "Yandex" },
  { name: "facebook", label: "Facebook" },
  { name: "instagram", label: "Instagram" },
  { name: "github", label: "Github" },
  { name: "gitlab", label: "Gitlab" },
  { name: "bitbucket", label: "Bitbucket" },
  { name: "gitee", label: "Gitee" },
  { name: "gitea", label: "Gitea" },
  { name: "discord", label: "Discord" },
  { name: "twitter", label: "Twitter" },
  { name: "kakao", label: "Kakao" },
  { name: "vk", label: "Vk" },
  { name: "linear", label: "Linear" },
  { name: "notion", label: "Notion" },
  { name: "monday", label: "Monday" },
  { name: "box", label: "Box" },
  { name: "spotify", label: "Spotify" },
  { name: "trakt", label: "Trakt" },
  { name: "twitch", label: "Twitch" },
  { name: "patreon", label: "Patreon" },
  { name: "strava", label: "Strava" },
  { name: "wakatime", label: "WakaTime" },
  { name: "livechat", label: "LiveChat" },
  { name: "mailcow", label: "MailCow" },
  { name: "planningcenter", label: "PlanningCenter" },
  { name: "oidc", label: "OIDC" },
] as const;

export type OAuth2ProviderName = (typeof oAuth2ProviderNames)[number]["name"];
export type OAuth2ProviderLabel = (typeof oAuth2ProviderNames)[number]["label"];
